# Brunnhaus Honig
stages:
  - hugo-build
update-website:
  stage: hugo-build
  only:
    - master
  allow_failure: false
  image: "registry.gitlab.com/brunnhaus/honig:latest"
  before_script:
    # prepare hugo
    - rm -rf public
  script:
    # build hugo site
    - hugo
    #- mv public ../
    # push rendered public folder to public branch
    #- git remote set-url origin git@gitlab.com:brunnhaus/honig.git
    #- (git stash && git stash drop && git checkout public) || git checkout public
    #- rm -rf public
    #- mv ../public .
    #- git add -A
    #- (git commit -m "cicd" && git push) || echo "no changes made"
