# Brunnhaus Honig
stages:
  - hugo-build
update-website:
  stage: hugo-build
  only:
    - master
  allow_failure: false
  image: "registry.gitlab.com/brunnhaus/honig:latest"
  before_script:
    # prepare hugo
    - rm -rf public
  script:
    # push rendered public folder to master branch
    - git remote set-url origin git@gitlab.com:brunnhaus/honig.git
    - git checkout master
    #- (git stash && git stash drop && git checkout public) || git checkout public
    # build hugo site
    - hugo
    - git add -f -A
    - (git commit -m "cicd" && git push) || echo "no changes made"
