baseURL: http://something-fresh.org/
languageCode: en-us
title: Honig
theme: hugo-fresh
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: false

params:
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
    image: logos/logo_wide.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: Imkerei Brunnhaus
    subtitle: "Verschiedene Honigsorten aus dem Isartal: Super Sommer, Fetter Frühling"
    image: favicon.png
    clientlogos:
      - supersommer_deckel
      - sommerbär_deckel
      - honigtrip_deckel
  section1:
    title: Honigsorten
    subtitle: mit den schönsten Etiketten
    tiles:
    - title: Super Sommer
      icon: supersommer
      text: This is some explanatory text that is on two rows
    - title: Sommer Bär
      icon: sommerbär
      text: This is some explanatory text that is on two rows
    - title: Honig Trip
      icon: honigtrip 
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section2:
    title: Unser Isartal Honig
    subtitle: Imkerei Brunnhaus
    features:
    - title: Direkt in der Natur
      text:  'Direkt am 300 Jahre alten, ehemalig "Königlichen Hofbrunnhaus an der Isar" stehen meine Buckfast Bienenstöcke im FFH Gebiet Isarauen unterhalb vom Biergarten Waldwirtschaft.'
      icon: beehive-outline
    - title: Ungespritzt
      text: 'Ungespritzte und vielfältige Pollen- und Nektarquellen stehen so meinen Bienen über das Jahr zur Verfügung wie z. B. Weide, Märzenbecher, Weißdorn, Kirschpflaume, Kirsche, Apfel, Felsenbirne, Löwenzahn, Roßkastanie, Linde, Natterkopf, Alpenclematis, Wildrosen und viele Wildblumen am Ufer der Isar.'
      icon: flower-outline
  section3:
    title:
    subtitle:
    image: bees.jpg
  section4:
    title: Ein paar Eindrücke
    subtitle: Von unseren Bienen
    image1: kästen.jpg
    image2: gläser.jpg
    image3: blume.jpg
    # clients:
    # - name: Irma Walters
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: Accountant
    #   img: 1
    # - name: John Bradley
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: Financial Analyst
    #   img: 2
    # - name: Gary Blackman
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: HR Manager
    #   img: 3
  section5: true
  footer:
    logo: logo.png
    # Social Media Title
    socialmediatitle: Folge uns
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      # Icons are from Font Awesome
    - link: https://gitlab.com/brunnhaus
      icon: git
    bulmalogo: false
    quicklinks:
      column1:
        title: "Honig"
        links:
        - text: Home
          link: /