baseURL: https://honig.brunnhaus.de/
languageCode: en-us
title: Imkerei Brunnhaus
theme: hugo-fresh
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: false

params:
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy 
  description: Leckere Honige von der Imkerei Brunnhaus
  navbarlogo:
    image: logos/logo_wide.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: Imkerei Brunnhaus
    subtitle: "Verschiedene Honigsorten aus dem Isartal: Super Sommer, Fetter Frühling, Honig Trip, ..."
    image: favicon.png
    clientlogos:
      - supersommer_deckel
      - honigtrip_deckel
      - sommerbär_deckel
      - fetterfrühling_deckel
      - frühlingsbär_deckel
  section1:
    title: Honigsorten
    subtitle: Der leckere Honig aus dem Isartal mit den coolsten Etiketten
    tiles:
    - title: Super Sommer '20
      icon: supersommer
      text: (Laborergebnisse noch nicht vorhanden)
      message: 
    - title: Honig Trip '20
      icon: honigtrip 
      text: Raps, Weide, Obst, Ahorn, Himbeere
      message: Ausverkauft
    - title: Sommer Bär '19
      icon: sommerbär
      text: Imker R. Seidl
      message: Ausverkauft
    - title: Frühlings Bär '19
      icon: frühlingsbär
      text: Imker R. Seidl
      message: Ausverkauft
    - title: Super Sommer '19
      icon: supersommer
      text: Linde, Himbeere, Kreuzblütler, Obst, Klee, Natterkopf, Roßkastanie, Wein
      message: Ausverkauft
    - title: Fetter Frühling '19
      icon: fetterfrühling
      text: Raps, Himbeere, Roßkastanie, Hartriegel, Hornklee, Linde, Ahorn
      message: Ausverkauft
  section2:
    title: Unser Isartal Honig
    subtitle: Imkerei Brunnhaus
    features:
    - title: Direkt in der Natur
      text:  'Direkt am 300 Jahre alten, ehemalig "Königlichen Hofbrunnhaus an der Isar" stehen meine Buckfast Bienenstöcke im FFH Gebiet Isarauen unterhalb vom Biergarten Waldwirtschaft.'
      icon: beehive-outline
    - title: Naturbelassen
      text: 'Ungespritzte und vielfältige Pollen- und Nektarquellen stehen so meinen Bienen über das Jahr zur Verfügung wie z. B. Weide, Märzenbecher, Weißdorn, Kirschpflaume, Kirsche, Apfel, Felsenbirne, Löwenzahn, Roßkastanie, Linde, Natterkopf, Alpenclematis, Wildrosen und viele Wildblumen am Ufer der Isar.'
      icon: flower-outline
    - title: Kontakt
      text: "Imker Dr. Ditmar Unger, [An der Isar 2, 82049 Pullach im Isartal.](https://google.de/search?q=Imkerei+Brunnhaus) Für Fragen und Anregungen bitte das Formular am Ende der Webseite nutzen."
      icon: map-marker
  section3:
    title:
    subtitle:
    image: supersommer_nah.jpg
  section4:
    title: Ein paar Eindrücke
    subtitle: von unserer Imkerei
    image1: biene.jpg
    image2: supersommer.jpg
    image3: kästen.jpg
    clients:
    - name: Ditmar
      quote: "Der Sommerhonig 2020 'Super Sommer' ist jetzt frisch geschleudert!"
      job: Hobbyimker
      img: d
    - name: Henny
      quote: "Meine Lieblingshonige!"
      job: Studentin
      img: h
    - name: Carolin
      quote: "Ohh, Du hast aber einen fähigen Designer!"
      job:
      img: x
  section5: true
  footer:
    logo: logo.png
    # Social Media Title
    socialmediatitle: Folge uns
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      # Icons are from Font Awesome
    - link: https://google.de/search?q=Imkerei+Brunnhaus
      icon: google
    - link: https://gitlab.com/brunnhaus
      icon: git
    quicklinks:
      column1:
        title: Impressum
        links:
        - text: Imker - Dr. Ditmar Unger
          link: https://brunnhaus.de
        - text: "Etiketten & Logos - Julian Lauer"
          link: https://julianlauer.de
        - text: "Webseite - Janek Lauer"
          link: https://schlauerlauer.de
        - text: "⠀"
        - text: Bienenstock Metriken in Grafana
          link: https://bienen.brunnhaus.de